'use strict';
const SAR={
 tetra(a){return [[a,a,a],[a,-a,-a],[-a,a,-a],[-a,-a,a]]},
 energy(y,p){let[x,v,L,w]=y,d=Math.max(Math.abs(x)-L,0);return .5*p.m*v*v+.5*p.k*x*x+.5*p.M*w*w+.5*p.K*(L-p.L0)**2+.5*p.kc*d*d},
 defaults(){return {m:1,k:4,c:.15,M:3,K:8,C:.5,kc:40,L0:.75,Lmax:2,amplitude:3,omega:1.7,dt:.002,compliant:true,energy_limit:100,settle_energy:1e-5,settle_seconds:1}},
 rhs(t,y,p,action){let[x,v,L,w]=y,d=Math.max(Math.abs(x)-L,0),f=action==='drive'?p.amplitude*Math.sin(p.omega*t):0;return[v,(f-p.c*v-p.k*x-p.kc*d*Math.sign(x))/p.m,p.compliant?w:0,p.compliant?(p.kc*d-p.K*(L-p.L0)-p.C*w)/p.M:0,f*v,p.c*v*v+(p.compliant?p.C*w*w:0),0]},
 propagate(t,y,p,action,stopEvents=[]){let h=p.dt,plus=(a,b,s)=>a.map((v,i)=>v+s*b[i]);let a=this.rhs(t,y,p,action),b=this.rhs(t+h/2,plus(y,a,h/2),p,action),c=this.rhs(t+h/2,plus(y,b,h/2),p,action),d=this.rhs(t+h,plus(y,c,h),p,action);let z=y.map((v,i)=>v+h*(a[i]+2*b[i]+2*c[i]+d[i])/6);if(z[2]<p.L0){let before=this.energy(z,p);z[2]=p.L0;z[3]=Math.max(0,z[3]);let delta=before-this.energy(z,p);z[6]+=delta;stopEvents.push({t:t+h,energy_correction:delta})}return z},
 closure(y,p,settled){return y.some(v=>!Number.isFinite(v))?'NUMERICAL_FAILURE':y[2]>p.Lmax?'CONSTRAINT_BREACH':settled>=p.settle_seconds?'STABLE':'CONTINUE'},
 simulate(p=this.defaults(),seconds=20,x0=.5,policy='drive'){
 let stopEvents=[],y=[x0,0,p.L0,0,0,0,0],e0=this.energy(y,p),t=0,settled=0,crossings=[],rows=[],audit=[],maxL=p.L0,status='CONTINUE';
 for(let step=0;step<Math.round(seconds/p.dt);step++){
 let constraint={Lmin:p.L0,Lmax:p.Lmax,energy_limit:p.energy_limit,admissible_actions:y[2]<=p.Lmax?['off','drive']:['off']};
 let evaluation={energy:this.energy(y,p),contact_extension:Math.max(Math.abs(y[0])-y[2],0),boundary_margin:p.Lmax-y[2]};
 let action=policy==='drive'&&constraint.admissible_actions.includes('drive')&&evaluation.energy<constraint.energy_limit?'drive':'off';
 let z=this.propagate(t,y,p,action,stopEvents);if(y[0]<0&&z[0]>=0&&z[0]!==y[0])crossings.push(t+p.dt*(-y[0])/(z[0]-y[0]));t+=p.dt;maxL=Math.max(maxL,z[2]);let en=this.energy(z,p);
 let inactive=policy==='off'||p.amplitude===0||p.omega===0;settled=en<=p.settle_energy&&inactive?settled+p.dt:0;status=this.closure(z,p,settled);
 if(step%50===0||status!=='CONTINUE'||step===Math.round(seconds/p.dt)-1){rows.push({t,x:z[0],v:z[1],L:z[2],w:z[3],energy:en,work:z[4],loss:z[5],stop_loss:z[6],total_loss:z[5]+z[6],energy_residual:en-e0-z[4]+z[5]+z[6],closure:status});audit.push({step,state_before:y.slice(0,4),constraint,evaluation,choice:action,state_after:z.slice(0,4),closure:status})}
 y=z;if(status!=='CONTINUE')break;
 }
 let periods=crossings.slice(1).map((v,i)=>v-crossings[i]),avg=periods.reduce((a,b)=>a+b,0)/periods.length;
 return {schema:'SAR-REM-RUN-2',parameters:p,initial:{x:x0,v:0},policy,sample_stride:50,summary:{closure:status,max_L:maxL,initial_energy:e0,final_energy:this.energy(y,p),work:y[4],loss:y[5],stop_loss:y[6],total_loss:y[5]+y[6],stop_event_count:stopEvents.length,energy_residual:this.energy(y,p)-e0-y[4]+y[5]+y[6],mean_crossing_rate_hz:periods.length?1/avg:null,period_cv:periods.length>=2?Math.sqrt(periods.reduce((s,v)=>s+(v-avg)**2,0)/periods.length)/avg:null},crossings,stop_events:stopEvents,rows,audit};
 },
 recover(start='',direction=''){let out=[];for(let s=0;s<4;s++)for(let d of [-1,1])if((start===''||s===+start)&&(direction===''||d===+direction))out.push({start:s,direction:d,vertices:Array.from({length:5},(_,k)=>(s+d*k+20)%4)});return out},
 reachable(edges,start){let s=new Set([start]);for(let i=0;i<edges.length;i++)for(let[a,b]of edges)if(s.has(a))s.add(b);return [...s].sort()},
 intensity(a,phase){let re=0,im=0;for(let i=0;i<a.length;i++){re+=a[i]*Math.cos(phase[i]);im+=a[i]*Math.sin(phase[i])}return re*re+im*im}
};
if(typeof module!=='undefined')module.exports=SAR;
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id);let run,index=0,playing=false,clock=0,active='mechanics';
const colors={ink:'#dde8ed',muted:'#8199a7',cyan:'#60ddc7',amber:'#ffc77b',red:'#ff8093',blue:'#79a9ff'};
function canvas(id){let c=$(id),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;let g=c.getContext('2d');g.scale(d,d);g.clearRect(0,0,r.width,r.height);return[g,r.width,r.height]}
function line(g,a,b,color,width=2){g.beginPath();g.moveTo(...a);g.lineTo(...b);g.strokeStyle=color;g.lineWidth=width;g.stroke()}
function text(g,t,x,y,color=colors.muted){g.fillStyle=color;g.font='12px system-ui';g.fillText(t,x,y)}
function dot(g,p,color,r=4){g.fillStyle=color;g.beginPath();g.arc(...p,r,0,2*Math.PI);g.fill()}
function dl(name,obj){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function build(){playing=false;$('play').textContent='Play';let p=SAR.defaults(),preset=$('preset').value,x0=.5,policy='drive',seconds=20;p.amplitude=+$('force').value;p.K=+$('stiffness').value;
if(preset==='fixed')p.compliant=false;if(preset==='free'){p.c=0;p.C=0;p.amplitude=0;policy='off'}if(preset==='damped'){p.c=1.5;p.amplitude=0;policy='off';seconds=25}if(preset==='breach'){p.Lmax=.751;x0=1.2;p.amplitude=0;policy='off'}
$('forceOut').textContent=p.amplitude.toFixed(1)+' N';$('stiffnessOut').textContent=p.K.toFixed(0)+' N/m';run=SAR.simulate(p,seconds,x0,policy);window.sarRun=run;index=run.rows.length-1;$('scrub').max=index;$('scrub').value=index;drawMechanics()}
function drawMechanics(){if(!run)return;let r=run.rows[index],p=run.parameters;let[g,w,h]=canvas('mechanical');let scale=Math.min(w*.22,h*.26)/Math.max(run.summary.max_L,.9),rot=.65;
let proj=([x,y,z])=>[w/2+(x*Math.cos(rot)-z*Math.sin(rot))*scale,h*.48-(y*.8+(x*Math.sin(rot)+z*Math.cos(rot))*.35)*scale];
for(let [a,col]of [[p.L0,colors.muted],[r.L,colors.cyan]]){let v=SAR.tetra(a).map(proj);for(let e of [[0,1],[0,2],[0,3],[1,2],[1,3],[2,3]])line(g,v[e[0]],v[e[1]],col,a===r.L?2:1);v.forEach(pt=>dot(g,pt,col))}
line(g,proj([-r.L,0,0]),proj([r.L,0,0]),colors.amber,2);dot(g,proj([0,0,0]),colors.ink,3);dot(g,proj([r.x,0,0]),colors.red,7);text(g,'Regular tetrahedron · generalized size L',16,26);text(g,'Gray: rest · Mint: boundary · Coral: x',16,h-22);
$('time').textContent=r.t.toFixed(2)+' s';$('boundary').textContent=r.L.toFixed(3)+' m';$('closure').textContent=r.closure;$('closure').style.color=['CONSTRAINT_BREACH','NUMERICAL_FAILURE'].includes(r.closure)?colors.red:colors.cyan;$('residual').textContent=r.energy_residual.toExponential(2)+' J';$('losses').textContent='Viscous loss: '+r.loss.toFixed(5)+' J · Stop correction: '+r.stop_loss.toFixed(5)+' J';$('frequency').textContent=run.summary.mean_crossing_rate_hz===null?'Not enough crossings':run.summary.mean_crossing_rate_hz.toFixed(4)+' Hz (whole run)';$('audit').textContent=JSON.stringify(run.audit[index],null,2);
let[c,cw,ch]=canvas('trace');let tmax=run.rows.at(-1).t,lim=Math.max(1.5,...run.rows.map(v=>Math.max(Math.abs(v.x),v.L)));let pt=(t,v)=>[42+t/tmax*(cw-62),ch/2-v/lim*(ch/2-25)];line(c,pt(0,0),pt(tmax,0),'#304855',1);for(let[key,col]of [['x',colors.red],['L',colors.cyan]]){c.beginPath();run.rows.forEach((v,i)=>{let p=pt(v.t,v[key]);i?c.lineTo(...p):c.moveTo(...p)});c.strokeStyle=col;c.lineWidth=2;c.stroke()}line(c,[pt(r.t,0)[0],15],[pt(r.t,0)[0],ch-20],colors.amber,1);text(c,'x(t)',10,18,colors.red);text(c,'L(t)',60,18,colors.cyan);text(c,tmax.toFixed(1)+' s',cw-55,ch-5);
}
function drawRecovery(){let start=$('start').value,dir=$('direction').value,hist=SAR.recover(start,dir);$('gamma').textContent=hist.length;$('recoverStatus').textContent=hist.length===1?'One history in the declared family':'History remains non-unique';$('histories').textContent=hist.map(h=>`${h.vertices.join(' → ')} · direction ${h.direction}`).join('\n');let[g,w,h]=canvas('glyph');let size=Math.min(w*.5,h*.6),left=(w-size)/2,top=(h-size)/2,pts=[[left,top+size],[left+size,top+size],[left+size,top],[left,top]];for(let i=0;i<4;i++){line(g,pts[i],pts[(i+1)%4],colors.cyan,3);dot(g,pts[i],colors.amber,5);text(g,String(i),pts[i][0]+10,pts[i][1]-10)}text(g,'Same square · different possible journeys',16,24);$('safe').textContent=hist.length===1?`Preserve · request observation · replay ${hist[0].vertices.join(' → ')}`:'Preserve trace · request an observation';}
function drawMemory(){let mode=$('memoryMode').value,own=[['A','B']],shared=mode==='shared'?[['B','C'],['C','D']]:mode==='duplicate'?[['A','B']]:[],edges=own.concat(shared),reach=SAR.reachable(edges,'A');$('reachable').textContent=reach.length+' / 4';let[g,w,h]=canvas('memoryCanvas'),pts={A:[w*.22,h*.3],B:[w*.65,h*.3],C:[w*.65,h*.74],D:[w*.22,h*.74]};for(let[a,b]of [['A','B'],['B','C'],['C','D']])line(g,pts[a],pts[b],edges.some(e=>e[0]===a&&e[1]===b)?colors.cyan:'#304855',3);for(let[k,p]of Object.entries(pts)){dot(g,p,reach.includes(k)?colors.cyan:colors.muted,13);text(g,k,p[0]-4,p[1]+4,'#07131b')}text(g,'Compatible action rules · start at A',16,24);$('memoryNote').textContent=mode==='shared'?'A→B plus B→C and C→D make C and D reachable under this declared rule set.':mode==='duplicate'?'A second copy of A→B adds no new transition or reachable state.':'The recipient knows only A→B. C and D remain inaccessible.';}
function drawPhasors(){let phase=+$('phase').value*Math.PI/180;let I=SAR.intensity([1,1],[0,phase]);$('phaseOut').textContent=$('phase').value+'°';$('intensity').textContent=I.toFixed(3);let[g,w,h]=canvas('phasors'),cx=w*.35,cy=h*.5,r=Math.min(w*.22,h*.32);g.beginPath();g.arc(cx,cy,r,0,2*Math.PI);g.strokeStyle='#304855';g.stroke();let a=[cx+r,cy],b=[cx+r*Math.cos(phase),cy-r*Math.sin(phase)],sum=[cx+r*(1+Math.cos(phase)),cy-r*Math.sin(phase)];line(g,[cx,cy],a,colors.cyan,3);line(g,[cx,cy],b,colors.amber,3);line(g,[cx,cy],sum,colors.red,3);text(g,'Coherent scalar amplitudes · A = 1 each',16,26);text(g,'Mint + amber → coral resultant',16,h-20);$('phasorEq').textContent=`I = |1 + exp(iφ)|² = 2 + 2 cos(φ) = ${I.toFixed(3)}`;}
function show(name){active=name;document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));redraw()}
function redraw(){if(active==='mechanics')drawMechanics();if(active==='recovery')drawRecovery();if(active==='memory')drawMemory();if(active==='phasors')drawPhasors()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));$('preset').onchange=build;$('force').onchange=build;$('stiffness').onchange=build;$('run').onclick=build;$('scrub').oninput=()=>{playing=false;$('play').textContent='Play';index=+$('scrub').value;drawMechanics()};$('play').onclick=()=>{playing=!playing;if(playing&&index>=run.rows.length-1)index=0;$('play').textContent=playing?'Pause':'Play'};$('export').onclick=()=>dl('sar-rem-mechanical-run.json',run);
$('start').onchange=drawRecovery;$('direction').onchange=drawRecovery;$('memoryMode').onchange=drawMemory;$('phase').oninput=drawPhasors;
$('packet').onclick=()=>dl('sar-rem-handoff-example.json',{schema:'SAR-REM-HANDOFF-1',author:'Steve Brown / SAR; synthetic example',field:'four fixed square vertices; one traversal; no lifts or retracing',raw_trace:[[0,0],[1,0],[1,1],[0,1],[0,0]],segmentation:'four ordered straight edges',evidence:[['start',0],['direction',1]],provenance:['synthetic-square-v1'],limits:'family-relative recovery; JSON export only, use Python packet for SHA-256 integrity check'});
window.addEventListener('resize',redraw);function frame(t){if(playing&&t-clock>75){clock=t;index++;if(index>=run.rows.length){index=run.rows.length-1;playing=false;$('play').textContent='Play'}$('scrub').value=index;if(active==='mechanics')drawMechanics()}requestAnimationFrame(frame)}build();requestAnimationFrame(frame);
}
